language: go
sudo: required

go:
- 1.7

before_install:
- sudo apt-get -qq update
- sudo apt-get install -y rpm
- gem install fpm
- make prepare

script:
- make rpm

deploy:
  provider: releases
  api_key:
    secure: GdJRA0e4DfK0Vn9nAV6IDir9r5kbeOxYnQupv7ghXFtCMYPSIAQO/t3yiPtAWPZma7IwtLw2+leYCescusQzwEA+PAqQBa1nd+Fl/JRr8nh/5TR5ymC+qzyfB6lPyZ/JAl4U1PPi+ByMBTcTpn+VvYr6z5F/i6MEjYrd/vCSixE=
  file_glob: true
  file:
  - build/frontreport
  - build/frontreport*.rpm
  skip_cleanup: true
  on:
    repo: skbkontur/frontreport
    tags: true
