language: go
sudo: required

go:
- 1.7

before_install:
- sudo apt-get -qq update
- sudo apt-get install -y rpm
- gem install fpm
- make prepare

script:
- make rpm

deploy:
  provider: releases
  api_key:
    secure: QtQbdw7Qb/blU8lRc7IIVC1Ai48mE4h8Y/tLgHbAa155hgAbhNURTQXc3AnlKGSPd997YJpXnckWnNuuyMp+8nwVcp+mmnrQUsjB+CZOjw/+aEIc3XYXar71NGZyOrmEa9hEYwoX9ltpnqwyd1eF5kkig0WVE7n+wILirsxheZ8=
  file_glob: true
  file:
  - build/frontreport
  - build/frontreport*.rpm
  skip_cleanup: true
  on:
    repo: skbkontur/frontreport
    tags: true
